CREATE TABLE `bf_goods` (
                            `id` int(11) NOT NULL AUTO_INCREMENT,
                            `appid` int(10) unsigned NOT NULL,
                            `buy_max_price` decimal(10,2) unsigned NOT NULL,
                            `buy_num` int(10) unsigned NOT NULL,
                            `game` varchar(255) NOT NULL DEFAULT '',
                            `name` varchar(255) NOT NULL DEFAULT '',
                            `market_hash_name` varchar(255) NOT NULL DEFAULT '',
                            `short_name` varchar(255) NOT NULL DEFAULT '',
                            `goods_id` int(10) unsigned NOT NULL,
                            `icon_url` varchar(255) NOT NULL DEFAULT '',
                            `steam_price` decimal(10,2) unsigned NOT NULL,
                            `steam_price_cny` decimal(10,2) unsigned NOT NULL,
                            `quick_price` decimal(10,2) unsigned NOT NULL,
                            `sell_min_price` decimal(10,2) unsigned NOT NULL,
                            `sell_num` int(10) unsigned NOT NULL,
                            `sell_reference_price` decimal(10,2) unsigned NOT NULL,
                            `steam_market_url` varchar(255) NOT NULL DEFAULT '',
                            `transacted_num` int(10) unsigned NOT NULL,
                            `steam_item_name_id` varchar(255) NOT NULL DEFAULT '',
                            `created_at` int(11) unsigned NOT NULL,
                            `updated_at` int(11) unsigned NOT NULL,
                            `steam_sell_price` decimal(10,2) unsigned NOT NULL,
                            PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14932 DEFAULT CHARSET=utf8;